-- MySQL Script generated by MySQL Workbench
-- 05/19/15 10:16:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- otro

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema controldeinventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controldeinventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controldeinventario` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `controldeinventario` ;

-- -----------------------------------------------------
-- Table `controldeinventario`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldeinventario`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Tipo_Usuario` VARCHAR(45) NOT NULL,
  `Ubicacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldeinventario`.`Equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldeinventario`.`Equipos` (
  `idEquipos` INT NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Ubicación` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEquipos`),
  INDEX `fk_Equipos_Usuario_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Equipos_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `controldeinventario`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldeinventario`.`Marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldeinventario`.`Marcas` (
  `idMarcas` INT NOT NULL,
  `Nombre_Marca` VARCHAR(45) NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `Equipos_idEquipos` INT NOT NULL,
  PRIMARY KEY (`idMarcas`),
  INDEX `fk_Marcas_Equipos1_idx` (`Equipos_idEquipos` ASC),
  CONSTRAINT `fk_Marcas_Equipos1`
    FOREIGN KEY (`Equipos_idEquipos`)
    REFERENCES `controldeinventario`.`Equipos` (`idEquipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldeinventario`.`Reparaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldeinventario`.`Reparaciones` (
  `idReparaciones` INT NOT NULL,
  `Fecha` VARCHAR(45) NOT NULL,
  `Equipos_idEquipos` INT NOT NULL,
  PRIMARY KEY (`idReparaciones`, `Equipos_idEquipos`),
  INDEX `fk_Reparaciones_Equipos1_idx` (`Equipos_idEquipos` ASC),
  CONSTRAINT `fk_Reparaciones_Equipos1`
    FOREIGN KEY (`Equipos_idEquipos`)
    REFERENCES `controldeinventario`.`Equipos` (`idEquipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
