-- MySQL Script generated by MySQL Workbench
-- 05/20/15 13:23:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema controldeinventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controldeinventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controldeinventario` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `controldeinventario` ;

-- -----------------------------------------------------
-- Table `controldeinventario`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldeinventario`.`Rol` (
  `idRol` INT NOT NULL,
  `Nombre_Rol` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldeinventario`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldeinventario`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Rol_idRol` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Rol1_idx` (`Rol_idRol` ASC),
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `controldeinventario`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldeinventario`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldeinventario`.`Marca` (
  `idMarca` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldeinventario`.`Modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldeinventario`.`Modelo` (
  `idModelo` INT NOT NULL,
  `Nombre_Modelo` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(45) NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  PRIMARY KEY (`idModelo`),
  INDEX `fk_Modelo_Marca1_idx` (`Marca_idMarca` ASC),
  CONSTRAINT `fk_Modelo_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `controldeinventario`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldeinventario`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldeinventario`.`Estado` (
  `idEstado` INT NOT NULL,
  `Nombre_Equipo` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldeinventario`.`Ubicación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldeinventario`.`Ubicación` (
  `idUbicacion` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUbicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldeinventario`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldeinventario`.`Tipo` (
  `idTipo` INT NOT NULL,
  `Tipo_Equipo` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldeinventario`.`Equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldeinventario`.`Equipos` (
  `idEquipos` INT NOT NULL,
  `Num_Serie` VARCHAR(45) NOT NULL,
  `Modelo_idModelo` INT NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  `Ubicacion_idUbicacion` INT NOT NULL,
  `Tipo_idTipo` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEquipos`),
  INDEX `fk_Equipos_Modelo1_idx` (`Modelo_idModelo` ASC),
  INDEX `fk_Equipos_Estado1_idx` (`Estado_idEstado` ASC),
  INDEX `fk_Equipos_Ubicación1_idx` (`Ubicacion_idUbicacion` ASC),
  INDEX `fk_Equipos_Tipo1_idx` (`Tipo_idTipo` ASC),
  INDEX `fk_Equipos_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Equipos_Modelo1`
    FOREIGN KEY (`Modelo_idModelo`)
    REFERENCES `controldeinventario`.`Modelo` (`idModelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipos_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `controldeinventario`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipos_Ubicación1`
    FOREIGN KEY (`Ubicacion_idUbicacion`)
    REFERENCES `controldeinventario`.`Ubicación` (`idUbicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipos_Tipo1`
    FOREIGN KEY (`Tipo_idTipo`)
    REFERENCES `controldeinventario`.`Tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipos_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `controldeinventario`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldeinventario`.`Reparaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldeinventario`.`Reparaciones` (
  `idReparaciones` INT NOT NULL,
  `Fecha_Reparacion` VARCHAR(45) NOT NULL,
  `Equipos_idEquipos` INT NOT NULL,
  `Hora_Reparacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idReparaciones`, `Equipos_idEquipos`),
  INDEX `fk_Reparaciones_Equipos1_idx` (`Equipos_idEquipos` ASC),
  CONSTRAINT `fk_Reparaciones_Equipos1`
    FOREIGN KEY (`Equipos_idEquipos`)
    REFERENCES `controldeinventario`.`Equipos` (`idEquipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controldeinventario`.`EquiposUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controldeinventario`.`EquiposUsuario` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
